alvos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from core import views

app_name='core'
urlpatterns=[
    #path('', views.home, name='home'),
    path('', views.alvos_list, name='list_alvos'),
    path('alvo_create/', views.alvo_create, name='alvo_create'),
    path('alvo_update/<int:pk>', views.alvo_update, name='alvo_update'),
    path('alvo_delete/<int:pk>', views.alvo_delete, name='alvo_delete'),
]

core/models.py
from django.db import models

class Alvo(models.Model):

    nome_alvo = models.CharField(
        max_length=100, 
        verbose_name='Nome do alvo',
        null=False,
        blank=False,
        help_text='Informe o nome do alvo'
        )
    lat = models.CharField(
        max_length=100, 
        verbose_name='Latitude',
        null=False,
        blank=False,
        help_text='Latitude'
        )
    lon = models.CharField(
        max_length=100, 
        verbose_name='Longitude',
        null=False,
        blank=False,
        help_text='Longitude'
        )
    data_expiracao = models.DateField(
        max_length=100, 
        verbose_name='Data de expiração',
        null=False,
        blank=False,
        help_text='Informe a data de expiração'
        )
        

    def __str__(self):
        return self.nome_alvo
    class Meta:
        verbose_name = 'Alvo'
        verbose_name_plural = 'Alvos'
        ordering = ['-nome_alvo']

core/views.py
from core.form import *
from core.models import *
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from django.template.loader import render_to_string



def home(request):
    alvo=Alvo.objects.all().order_by('-id')
    template_name="core/alvos_list_home.html"
    context={'alvo':alvo}
    return render(request, template_name, context)

def alvos_list(request):
    alvo=Alvo.objects.all().order_by('-id')
    template_name="core/alvos_list.html"
    context={'alvo':alvo}
    return render(request, template_name, context)


def save_alvos_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            alvo=Alvo.objects.all().order_by('-id')
            data['html_alvo_list'] = render_to_string('core/includes/partial_alvo_list.html', {
                'alvo': alvo
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)



def alvo_create(request):
    if request.method == 'POST':
        form = AlvoForm(request.POST)
    else:
        form = AlvoForm()
    return save_alvos_form(request, form, 'core/includes/partial_alvo_create.html')

def alvo_update(request, pk):
    alvo=get_object_or_404(Alvo, pk=pk)
    if request.method=="POST":
        form=AlvoForm(request.POST, instance=alvo)
    else:
        form=AlvoForm(instance=alvo)
    return save_alvos_form(request, form, 'core/includes/partial_alvo_update.html')

def alvo_delete(request, pk):
    alvo=get_object_or_404(Alvo, pk=pk)
    data=dict()
    if request.method=='POST':
        alvo.delete()
        data['form_is_valid']=True
        alvo=Alvo.objects.all().order_by('-id')
        data['html_alvo_list']=render_to_string('core/includes/partial_alvo_list.html', {
            'alvo':alvo
        })
    else:
        context={'alvo':alvo}
        data['html_form']=render_to_string('core/includes/partial_alvo_delete.html', context, request=request)
    return JsonResponse(data)

templates/core/alvos_list.html
<html>
  <head>
    <title>LISTA DE ALVOS</title>
  </head>


  <body>
    
  
  <div class="btn-group" style="z-index: 1001; margin: 5px;">
    <!--<button type="buttons" id="others" class="btn btn-default">NOVO ALVO</button>-->

    <button type="button" class="btn btn-primary js-create-alvo" data-url="{% url 'core:alvo_create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      Novo alvo
    </button>
  </div>

{% include 'core/includes/partial_alvo_list.html' %}

<div class="modal" id="modal-alvo">
  <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
      </div>
    </div>
</div>

</body>
</html>
  

templates/core/base.html
{% load static %}<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD DE ALVOS</title>
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">

     

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    
    <script src="{% static 'core/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/core/includes/partial_alvo_create.html
<form method="post" action="{% url 'core:alvo_create' %}" class="js-alvo-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Criar novo alvo</h4>
  </div>
  <div class="modal-body">
    {% include 'core/includes/partial_alvo_form.html' %}

    
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary">Criar alvo</button>
  </div>
</form>

templates/core/includes/partial_alvo_delete.html
<form method="post" action="{% url 'core:alvo_delete' alvo.id %}" class="js-alvo-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirmar operação</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Deseja eliminar o alvo <strong>{{ alvo.nome_alvo }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-danger">Eliminar alvo</button>
  </div>
</form>

templates/core/includes/partial_alvo_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/core/includes/partial_alvo_list.html
{% load static %}

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" rel="stylesheet"/>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>

<script src="{% static 'core/js/alvos.js' %}"></script>








<body>

  
  


  <!--<div id="map"></div>-->

  <div id="map" >
  
  </div>

  


  <div aria-labelledby="myModalLabel" class="modal left fade" id="emptymodal" role="dialog" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Alvo nº <strong id="idalvo"></strong></h4>
        </div>
        <div class="modal-body">

          <h1 class="text-primary" > Nome do alvo: <br><b id="nomedetailalvo"> </b> </h1>
          <hr>
          <h3 class="text-success" > Data de expiração: <br><b id="datedetailalvo"></b></h3>
        </div>
        <div class="modal-footer">
     
    <button type="button" id="btn_update" class="btn btn-primary js-create-alvo" data-url="{% url 'core:alvo_update' 1 %}">
      <span class="glyphicon glyphicon-edit"></span>
      Editar alvo
    </button>

    <button type="button" id="btn_update" class="btn btn-danger js-create-alvo" data-url="{% url 'core:alvo_delete' 1 %}">
      <span class="glyphicon glyphicon-trash"></span>
      Eliminar alvo
    </button>

          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>

        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

<script>


// Where you want to render the map.
var element = document.getElementById('map');

// Height has to be set. You can do this in CSS too.
element.style = 'width:auto; height:100%';



  /*Custom marker */
PlaceMarker = L.CircleMarker.extend({
  options: {
    id: ''
  }
});
/*Include the marker data and create the layers */
var data = [
{% for alvo in alvo %} 

["{{ alvo.nome_alvo }}" , "{{ alvo.data_expiracao }}", "{{ alvo.id }}", {{alvo.lat}}, {{ alvo.lon }}],

{% empty %}

["Angola", "1", -8.83682, 13.23432],




{% endfor %}

];
var layer = new L.LayerGroup();
for (var i = 0; i < data.length; i++) {
    marker = new PlaceMarker([data[i][3], data[i][4]], {
      color: "red",
      name: data[i][0],
      date: data[i][1],
      id: data[i][2],

    }).addTo(layer).on('click', markerOnClick);
  
}


/* Some handy variables*/
var booklayers = [layer]
  /*Initialise map; change zoom control position*/
var map = L.map('map', {
  layers: booklayers
}).setView([-8.83682, 13.23432], 12.5);
map.zoomControl.setPosition('bottomright');
/*Add tileLayers*/
mapLink = '<a href="http://openstreetmap.org">OpenStreetMap<\/a>';
L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  attribution: '&copy; ' + mapLink + ' Contributors',
  maxZoom: 18,
}).addTo(map);
/* Open modal & center map on marker click 	*/
function markerOnClick(e) {
  var id = this.options.id;
  var name = this.options.name;
  var date = this.options.date;


  //$(".modal-body").html('This is marker ' + id);
  $("#idalvo").html(id);
  $("#nomedetailalvo").html(name);
  $("#datedetailalvo").html(date);

  //$("#btn_update").html(id);

 


  $('#emptymodal').modal('show');
  map.setView(e.target.getLatLng());
  e.preventDefault();
}
/*Close modal on map click */
map.on('click', function(e) {
  $('.modal').modal('hide');
});


 

</script>





</body>

templates/core/includes/partial_alvo_update.html
<form method="post" action="{% url 'core:alvo_update' form.instance.pk %}" class="js-alvo-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Editar alvo</h4>
  </div>
  <div class="modal-body">
    {% include 'core/includes/partial_alvo_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">
      <span class="glyphicon glyphicon-edit"></span>

      Atualizar Alvo</button>
 
    <!--<button type="button"
    class="btn btn-danger btn-sm js-delete-alvo"
    data-url="#myModal2"> Eliminar Alvo</button>-->

    <a data-toggle="modal"  href="#myModal2" class="btn btn-danger">
      <span class="glyphicon glyphicon-trash"></span>

       Eliminar Alvo
      
    </a>

    
    
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>

  </div>
</form>


<div class="modal" id="myModal2" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
    
      <div class="modal-body">

        <form method="post" action="{% url 'core:alvo_delete' form.instance.pk %}" class="js-alvo-delete-form">
          {% csrf_token %}
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title">Confirmar operação</h4>
          </div>
          <div class="modal-body">
            <p class="lead">Deseja eliminar o alvo <strong>{{ form.instance.nome_alvo }}</strong>?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="submit"  class="btn btn-danger">Eliminar alvo</button>
          </div>
        </form>

      
      
      </div>
    
    </div>
  </div>
</div>


<script>


var originalModal = $('#myModal2').clone();
$(document).on('#myModal2', 'hidden.bs.modal', function () {
    $('#myModal2').remove();
    var myClone = originalModal.clone();
    $('body').append(myClone);
});


</script>